WebTrans/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webfortrans/', include('webfortrans.urls',namespace='webfortrans')),

]

webfortrans/urls.py
from django.urls import path,re_path
from webfortrans import views

app_name='webfortrans'

urlpatterns=[
    # path('index.html',views.index,name='translate'),
    path('index_1.html',views.index_1,name='translate_1'),
    path('index_2.html',views.index_2,name="translate_2"),
    path('index_3.html',views.index_3,name="translate_3"),
    path('get_trans/',views.get_trans,name='get_trans'),
    path('index_demo.html',views.index_demo,name="index_demo"),
    path('add_punc/',views.add_punc,name='add_punc'),
    path('get_corpus/',views.get_corpus,name='get_corpus'),
    path('get_dict/',views.get_dict,name='get_dict'),

]

webfortrans/models.py
from django.db import models

# Create your models here.
class Corpus(models.Model):
    old=models.CharField(max_length=1000)
    new=models.CharField(max_length=1000)
    title=models.CharField(max_length=40)
    def __str__(self):
        return str(self.id)

# 词典
class Dictionary(models.Model):
    key=models.CharField(max_length=10)
    value=models.CharField(max_length=1000)
    def __str__(self):
        return str(self.id)

webfortrans/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .my_code import ClassForWeb
import jieba
# Create your views here.

# jieba.load_userdict("D:\CSE\jetbrains\pycharm\WebTrans\webfortrans\myfiles\dict.txt")
# jieba.load_userdict("D:\CSE\jetbrains\pycharm\WebTrans\webfortrans\myfiles\中国历史地名词典.txt")
# jieba.load_userdict("D:\CSE\jetbrains\pycharm\WebTrans\webfortrans\myfiles\古代人名（25w）.txt")
# jieba.load_userdict("D:\CSE\jetbrains\pycharm\WebTrans\webfortrans\myfiles\成语（5W）.txt")
# tfidf = analyse.extract_tags
# keywords=tfidf("加载")
# print(keywords)
# 将所有服务做成类然后在这部分预加载。

get_keyword=ClassForWeb.Tf_tiqu()

# def index(request):
#     '''
#     :param request: 提供的请求
#     :return:
#     '''
#     if request.method=="GET":
#         print("get method")
#         return render(request, 'version-02/index.html')
#     else:
#         print(request.POST)
#         src=request.POST.get('input')
#         if len(src.strip())==0:
#             return render(request, 'version-02/index.html')
#         # 前端提交古文到现代文翻译
#         if "old2new.x" in request.POST:
#             print('old2new')
#             Demo=ClassForWeb.get_full_translate(get_keyword, src, src)
#             return render(request, 'version-02/index.html',{'Demo':Demo})
#
#         # 前端提交添加标点
#         if "autopunc.x" in request.POST:
#             print('autopunc')
#             Demo = ClassForWeb.auto_add_punctuation(get_keyword, src, src)
#             return render(request, 'version-02/index.html',{'Demo':Demo})
#
#         # 前端提交现代文到古文
#         if "new2old.x" in request.POST:
#             print("new2old")
#             Demo = ClassForWeb.get_back_translate(get_keyword, src, src)
#             return render(request, 'version-02/index.html',{'Demo':Demo})

def get_trans(request):
    src=request.GET['src']
    res_dict={'tgt':src}
    return JsonResponse(res_dict)

def add_punc(request):
    src=request.GET['src']
    res_dict={'tgt':src+'!'}
    return JsonResponse(res_dict)

def get_corpus(request):
    src = request.GET['src']
    res="src:"+src+'\n'+"title:**title**"+"\n\n"
    res_cor={'tgt':res}
    return JsonResponse(res_cor)

def get_dict(request):
    src=request.GET['src']
    res=src
    res_cor={'tgt':res}
    return  JsonResponse(res_cor)



def index_demo(request):
    return render(request, 'version-02/index.html')


def index_1(request):
    return render(request,'version-03/index_1.html')

def index_2(request):
    return render(request,'version-03/index_2.html')

def index_3(request):
    return render(request,'version-03/index_3.html')

webfortrans/templates/version-02/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html class="nojs html css_verticalspacer" lang="zh-CN">
 <head>

  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2018.0.0.379"/>
  
  <script type="text/javascript">
   // Update the 'nojs'/'js' class on the html node
document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');

// Check that all required assets are uploaded and up-to-date
if(typeof Muse == "undefined") window.Muse = {};window.Muse.assets = {"required":["{% static "version_2/scripts/museutils.js" %}","{% static "version_2/scripts/museconfig.js" %}""{% static "version_2/scripts/musewpslideshow.js" %}","{% static "version_2/scripts/jquery.museoverlay.js" %}","{% static "version_2/scripts/touchswipe.js" %}","{% static "version_2/scripts/jquery.watch.js" %}","{% static "/version_2/css/index.css" %}"], "outOfDate":[]};
</script>
     <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
     <script>
         $(document).ready(function () {
             $('#u99').click(function () {
                 var src=$('#src_get').val();

                 $.getJSON('{% url 'webfortrans:get_trans' %}',{'src':src},function (ret) {
                     {#$('#tgt_out').pop()#}
                     $('#tgt_out').val(ret.tgt)
                     {#$('#tgt_out').append(ret.tgt)#}
                 })
             })
             $('#u103').click(function () {
                 var src=$('#src_get').val();

                 $.getJSON('{% url 'webfortrans:add_punc' %}',{'src':src},function (ret) {
                     $('#tgt_out').val(ret.tgt)
                 })
             })
             $('#u112').click(function () {
                 var src=$('#src_get').val();
                 $.getJSON('{% url 'webfortrans:get_corpus' %}',{'src':src},function (ret) {
                        $('#corpus').val(ret.tgt)
                 })

             })
             $('#u120').click(function () {
                 var src=$('#src_get').val();
                 $.getJSON('{% url 'webfortrans:get_dict' %}',{'src':src},function (ret) {
                        $('#dict').val(ret.tgt)
                 })

             })
         })
     </script>
  
  <title>古文翻译</title>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{% static "version_2/css/site_global.css" %}"/>
  <link rel="stylesheet" type="text/css" href="{% static "version_2/css/master_a-__.css" %}"/>
  <link rel="stylesheet" type="text/css" href="{% static "version_2/css/index.css" %}" id="pagesheet"/>
   </head>
 <body>

  <div class="clearfix" id="page"><!-- column -->
{#      <form action="{% url 'webfortrans:translate' %}" method="POST">#}
{#          {% csrf_token %}#}
   <div class="position_content" id="page_position_content">
    <div class="clearfix colelem" id="pu94"><!-- group -->
     <div class="clip_frame grpelem" id="u94"><!-- image -->
      <img class="block" id="u94_img" src="{% static "version_2/images/2-%e5%9b%be%e7%89%8713-crop-u94.png" %}" alt="" width="1160" height="58"/>
     </div>
     <div class="rounded-corners clearfix grpelem" id="u138"><!-- group -->
      <img class="grpelem" id="u139-4" alt="古文翻译" width="224" height="58" src="{% static "version_2/images/u139-4.png" %}"/><!-- rasterized frame -->
     </div>
    </div>

    <div class="clearfix colelem" id="pbuttonu98"><!-- group -->
     <div class="Button rounded-corners clearfix grpelem" id="buttonu98"><!-- container box -->
{#      <img class="grpelem" id="u99" alt="古文→现代文" type='submit' src="{% static "version_2/images/blank.gif" %}"/><!-- state-based BG images -->#}
         <input type="image" class="grpelem" id="u99" alt="古文→现代文" name="old2new" src="{% static "version_2/images/blank.gif" %}"  οnclick="document.formName.submit()">
     </div>
     <div class="Button rounded-corners clearfix grpelem" id="buttonu100"><!-- container box -->
{#      <img class="grpelem" id="u101" alt="现代文→古文" src="{% static "version_2/images/blank.gif" %}"/><!-- state-based BG images -->#}
         <input type="image" class="grpelem" id="u101" alt="现代文→古文" name="new2old" src="{% static "version_2/images/blank.gif" %}"  οnclick="document.formName.submit()">
     </div>
     <div class="Button rounded-corners clearfix grpelem" id="buttonu102"><!-- container box -->
{#      <img class="grpelem" id="u103" alt="古文自动加标点" src="{% static "version_2/images/blank.gif" %}"/><!-- state-based BG images -->#}
         <input type="image" class="grpelem" id="u103" alt="古文自动加标点" name="autopunc" src="{% static "version_2/images/blank.gif" %}"  οnclick="document.formName.submit()">
     </div>
    </div>

    <div class="clearfix colelem" id="pu96"><!-- group -->
     <div class="rounded-corners grpelem" id="u96"><!-- simple frame --></div>
     <div class="rounded-corners grpelem" id="u97"><!-- simple frame --></div>
     <div class="PamphletWidget clearfix grpelem" id="pamphletu104"><!-- none box -->
      <div class="popup_anchor" id="u105popup">
       <div class="ContainerGroup clearfix" id="u105"><!-- stack box -->
        <div class="Container clearfix grpelem" id="u106"><!-- group -->
         <div class="clearfix grpelem" id="u107-13"><!-- content -->
         <textarea id='corpus' style="border:0;background-color:transparent;color:#666464;width: 500px;height: 240px;padding: 10px;" readonly='readonly'>
            {% for cor_dic in Demo.tgt_corpus %}
原文：{{ cor_dic.old }}
译文：{{ cor_dic.new }}
出处：《{{ cor_dic.title }}》
            {% endfor %}
         </textarea>
          <p>&nbsp;</p>
         </div>
        </div>
       </div>
      </div>
      <div class="ThumbGroup clearfix grpelem" id="u110"><!-- none box -->
       <div class="popup_anchor" id="u111popup">
        <div class="Thumb popup_element clearfix" id="u111"><!-- group -->
         <img class="grpelem" id="u112" alt="语料库" src="{% static "version_2/images/blank.gif" %}"/><!-- state-based BG images -->
        </div>
       </div>
      </div>
     </div>
     <div class="PamphletWidget clearfix grpelem" id="pamphletu117"><!-- none box -->
      <div class="popup_anchor" id="u123popup">
       <div class="ContainerGroup clearfix" id="u123"><!-- stack box -->
        <div class="Container clearfix grpelem" id="u124"><!-- group -->
         <div class="clearfix grpelem" id="u125-17"><!-- content -->
           <textarea id="dict" style="border:0;background-color:transparent;color:#666464;width: 500px;height: 240px;padding: 10px;" readonly='readonly'>
{% for x in Demo.tgt_dic %}
{{ x.key }}
{% for l in x.value %}
{{ l }}
{% endfor %}
{% endfor %}
           </textarea>
          <p>&nbsp;</p>
         </div>
        </div>
       </div>
      </div>
      <div class="ThumbGroup clearfix grpelem" id="u118"><!-- none box -->
       <div class="popup_anchor" id="u119popup">
        <div class="Thumb popup_element clearfix" id="u119"><!-- group -->
         <img class="grpelem" id="u120" alt="字典" src="{% static "version_2/images/blank.gif" %}"/><!-- state-based BG images -->
        </div>
       </div>
      </div>
     </div>
     <div class="clip_frame grpelem" id="u130"><!-- image -->
      <img class="block" id="u130_img" src="{% static "version_2/images/12-11.png" %}" alt="" width="198" height="144"/>
     </div>

     <div class="clip_frame grpelem" id="u132"><!-- image -->
      <img class="block" id="u132_img" src="{% static "version_2/images/2-%e5%9b%be%e7%89%8716-crop-u132.png" %}" alt="" width="560" height="240"/>
     </div>
     <div class="clip_frame clearfix grpelem" id="u134"><!-- image -->
      <img class="position_content" id="u134_img" src="{% static "version_2/images/2-%e5%9b%be%e7%89%8718.png" %}" alt="" width="560" height="299"/>
     </div>
     <div class="clearfix grpelem" id="u136-4"><!-- content -->
      <textarea	name="input" id="src_get" style="border:0;background-color:transparent;color:#666464;width: 500px;height: 150px;padding: 10px;font-family: 'Adobe 仿宋 Std R' " placeholder="输入需要翻译的内容">{{ Demo.src }}</textarea>
     </div>
     <div class="clearfix grpelem" id="u137-4"><!-- content -->
      <textarea	id="tgt_out" style="border:0;background-color:transparent;color:#000000;width: 500px;height: 150px;padding: 10px;" readonly='readonly'>{{ Demo.tgt_model }}</textarea>
     </div>
    </div>
    <div class="verticalspacer" data-offset-top="0" data-content-above-spacer="825" data-content-below-spacer="97"></div>
   </div>
{#      </form>#}
  </div>

  <div class="preload_images">
   <img class="preload" src="{% static "version_2/images/u99-r.png" %}" alt=""/>
   <img class="preload" src="{% static "version_2/images/u101-r.png" %}" alt=""/>
   <img class="preload" src="{% static "version_2/images/u103-r.png" %}" alt=""/>
   <img class="preload" src="{% static "version_2/images/u112-r.png" %}" alt=""/>
   <img class="preload" src="{% static "version_2/images/u112-a.png" %}" alt=""/>
   <img class="preload" src="{% static "version_2/images/u120-r.png" %}" alt=""/>
   <img class="preload" src="{% static "version_2/images/u120-a.png" %}" alt=""/>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   // Decide weather to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(d){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},c=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},g=function(g){for(var f=document.getElementsByTagName("link"),h=0;h<f.length;h++)if("text/css"==f[h].type){var i=(f[h].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!i||!i[1]||!i[2])break;b[i[1]]=i[2]}f=document.createElement("div");f.className="version";f.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(f);for(h=0;h<Muse.assets.required.length;){var i=Muse.assets.required[h],l=i.match(/([\w\-\.]+)\.(\w+)$/),k=l&&l[1]?
l[1]:null,l=l&&l[2]?l[2]:null;switch(l.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");f.className+=" "+k;k=a(c(f,"color"));l=a(c(f,"backgroundColor"));k!=0||l!=0?(Muse.assets.required.splice(h,1),"undefined"!=typeof b[i]&&(k!=b[i]>>>24||l!=(b[i]&16777215))&&Muse.assets.outOfDate.push(i)):h++;f.className="version";break;case "js":h++;break;default:throw Error("Unsupported file type: "+l);}}d?d().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
f.parentNode.removeChild(f);if(Muse.assets.outOfDate.length||Muse.assets.required.length)f="服务器上的某些文件可能缺失或不正确。请在清除浏览器高速缓存后重试。如果问题仍然存在，请联系网站作者。",g&&Muse.assets.outOfDate.length&&(f+="\nOut of date: "+Muse.assets.outOfDate.join(",")),g&&Muse.assets.required.length&&(f+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(f+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(f)):alert(f)};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){g(!0)},5E3):g()}};
var muse_init=function(){require.config({baseUrl:"/static/version_2"});require(["jquery","museutils","whatinput","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.watch"],function(d){var $ = d;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('#pamphletu104', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'mouseover',deactivationEvent:'',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:false,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu104 */
Muse.Utils.initWidget('#pamphletu117', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'mouseover',deactivationEvent:'',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:false,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu117 */
Muse.Utils.fullPage('#page');/* 100% height page */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="{% static "version_2/scripts/require.js" %}" type="text/javascript" async data-main="{% static "version_2/scripts/museconfig.js" %}" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>